spring:
  application:
    name: db
  datasource:
    url:  jdbc:mariadb://localhost:3306/intellij_test
    username: root
    password: A1.b2,c3-
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update